baseURL = "https://dan.cardamore.ca/"
description = "My Blog on the nets"
languageCode = "en-us"
title = "Dan Cardamore's Blog"
copyright = "Copyright © 2019 Dan Cardamore, all rights reserved"
#theme = "slick"
# googleAnalytics = "TODO Tracking code"

[params]
  homeText = "Welcome to Dan's blog"
  dateFormat = "Jan 2, 2006"

[permalinks]
  blog = "/:filename/"

[menu]

  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  # [[menu.main]]
  #   name = "Blog"
  #   pre = "edit"
  #   url = "/blog/"
  #   weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
  tag = "tags"
